version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    reviewers:
      - "fordanic"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "github_actions"

  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    reviewers:
      - "fordanic"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "weekly" }
    reviewers:
      - "fordanic"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "docker"
