services:
  stt:
    build: ./services/stt
    ports:
      - "8101:8000"
  translate:
    build: ./services/translate
    ports:
      - "8102:8000"
  tts:
    build: ./services/tts
    ports:
      - "8103:8000"
