services:
  stt:
    build:
      context: .
      dockerfile: ./services/stt/Dockerfile
    ports:
      - "8101:8000"
  translate:
    build: 
      context: .
      dockerfile: ./services/translate/Dockerfile
    ports:
      - "8102:8000"
  tts:
    build:
      context: .
      dockerfile: ./services/tts/Dockerfile
    ports:
      - "8103:8000"
