# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: language_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "language_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16language_service.proto\x12\x0c\x66\x61ithecho.v1"2\n\nAudioChunk\x12\x0e\n\x06pcm16k\x18\x01 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03"A\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03"0\n\x0bSpeechChunk\x12\x0b\n\x03\x61\x61\x63\x18\x01 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03"8\n\x0bLangRequest\x12\x13\n\x0bsource_lang\x18\x01 \x01(\t\x12\x14\n\x0ctarget_langs\x18\x02 \x03(\t"&\n\x0cLangResponse\x12\x16\n\x0e\x61\x63\x63\x65pted_langs\x18\x01 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "language_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUDIOCHUNK"]._serialized_start = 40
    _globals["_AUDIOCHUNK"]._serialized_end = 90
    _globals["_TEXTCHUNK"]._serialized_start = 92
    _globals["_TEXTCHUNK"]._serialized_end = 157
    _globals["_SPEECHCHUNK"]._serialized_start = 159
    _globals["_SPEECHCHUNK"]._serialized_end = 207
    _globals["_LANGREQUEST"]._serialized_start = 209
    _globals["_LANGREQUEST"]._serialized_end = 265
    _globals["_LANGRESPONSE"]._serialized_start = 267
    _globals["_LANGRESPONSE"]._serialized_end = 305
# @@protoc_insertion_point(module_scope)
